version: '3.8'

services: 
    api:
        build: ./api
        ports: 
            - '5000:5000'
        depends_on: 
            - database
    database:
        image: 'mongo:4.0.20'
        environment: 
            - MONGO_INITDB_DATABASE=swapiIvterview
            - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
        volumes: 
            - ./mongodata:/data/db
        ports: 
            - '27017:27017'